### ISSUE TITLE
Loss can't autograd

### ISSUE THREAD

**Issue by Mumuqiao** [CodeWZT/MLVSNet#1]
My config setting:

>Namespace(batchSize=32, category_name='Cyclist', data_dir='/home/xxx/KITTI/training', goon=False, input_feature_num=0, learning_rate=0.001, manualSeed=1, model='netR_goon.pth', nepoch=60, ngpu=1, optimizer='optimizer_goon.pth', save_root_dir='tiny_test_results', split='Train TINY', workers=4)

When I run train_tracking.py
>Traceback (most recent call last):
  File "train_tracking.py", line 180, in <module>
    loss.backward()
  File "/home/xxx/.conda/envs/pp/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/xxx/.conda/envs/pp/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Expected isFloatingType(grads[i].type().scalarType()) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

It goes wrong.

My environment setting totaly follows the `readme.md`

**Comment by CodeWZT** [comment]
Hello, this problem may be caused by the version of pointnet2. You can refer to this link.`https://github.com/qiqihaer/votenet-kitti/issues/5`。

**Comment by Mumuqiao** [comment]
> Hello, this problem may be caused by the version of pointnet2. You can refer to this link.`https://github.com/qiqihaer/votenet-kitti/issues/5`。

THANKS! It works for me!
